fails:Kernel.at_exit allows calling exit inside at_exit handler
